<?php

use App\Models\Locations\Locations;
use Illuminate\Database\Seeder;

class LocationsSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            [
                'name' => 'sarit',
                'description' => 'sarit centre',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3153.565017836055!2d-122.41879278507707!3d37.77679637975909!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8085809c6c8f4459%3A0xb10ed6d9b5050fa5!2sTwitter+HQ!5e0!3m2!1sen!2sro!4v1524131359924',
            ],
            [
                'name' => 'muindi mbingu (mbk)',
                'description' => 'jevanjee gardens',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'two rivers',
                'description' => 'two rivers mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'westgate',
                'description' => 'westgate mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'biashara',
                'description' => 'the bazaar',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'village market',
                'description' => 'village mrkt',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'ridgeways mall',
                'description' => 'kiambu mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tropical crafts',
                'description' => 'muindi mbingu str',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'highridge bata',
                'description' => 'diamond plaza bldg',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nairobi 3',
                'description' => 'river road',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kiambu 2',
                'description' => 'kiambu town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'ol talet mall',
                'description' => 'ol talet mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'narok',
                'description' => 'narok',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kiambu one',
                'description' => 'nairobi-kiambu rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivas moi ave',
                'description' => 'moi avenue',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tom mboya mega',
                'description' => 'tom mboya street opposite odeon',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'c.d. outlet',
                'description' => 'bata main gate- limuru',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nakuru two',
                'description' => 'kenyatta str.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'greenspan',
                'description' => 'greenspan mall donholm',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tom mboya 2',
                'description' => 'tom mboya street opposite post office',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nakuru four',
                'description' => 'westside mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nakuru one',
                'description' => 'kenyatta str.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nakuru three',
                'description' => 'pandit nehru road',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'embakasi destination',
                'description' => 'pipeline',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'buru bata ',
                'description' => 'buruburu complex',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivasha bata',
                'description' => 'naivasha/nku rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivas nakuru',
                'description' => 'nakuru',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'the point buru',
                'description' => 'naivas - buru',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'buffalo mall',
                'description' => 'naivasha/nku rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'eldama ravine',
                'description' => 'roza plaza',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'gilgil - spears',
                'description' => 'gilgil',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivas naivasha',
                'description' => 'naivasha/nku rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tuskys imani nakuru',
                'description' => 'nakuru',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'new kenshoes',
                'description' => 'moi avenue',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'la galleria',
                'description' => 'langata rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'capital centre',
                'description' => 'mombasa road',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'likat btq',
                'description' => 'mfangano str',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 't-mall',
                'description' => 'mbagathi rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'gateway mall',
                'description' => 'syokimau',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kitengela',
                'description' => 'kenol kobil kitesh',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'machakos two',
                'description' => 'ngei road',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'machakos one',
                'description' => 'lokindo road',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'k mall',
                'description' => 'komarock',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],

            [
                'name' => ' utawala 2',
                'description' => 'naivas supermarket',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'southfield mall',
                'description' => 'embakasi',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivas kitengela',
                'description' => 'kitengela',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mulleys kitui',
                'description' => 'kitui town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tumaini utawala',
                'description' => 'tumaini supermarket utawala',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'langata mall',
                'description' => 'langata mall nairobi',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'lang\'ata hyper',
                'description' => 'langata hyper market',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mulleys mlolongo',
                'description' => 'mlolongo',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'shujaa mall',
                'description' => 'kayole',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'bata hilton',
                'description' => 'opposite kencom',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'alibhai shariff',
                'description' => 'kimathi street',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nairobi 1 (680)',
                'description' => 'kenyatta str. nairobi',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'new junction',
                'description' => 'dagoretti rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'yaya',
                'description' => 'yaya centre',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'bata rongai',
                'description' => 'rongai town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'karen crossrds',
                'description' => 'karen centre',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'milele mall',
                'description' => 'milele mall ngong',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'karen hub',
                'description' => 'the hub karen mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'prestige plaza',
                'description' => 'prestige plaza',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'jubilee bata ',
                'description' => 'mama ngina street',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 're-plaza',
                'description' => 'aga khan walk',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'maasai mall',
                'description' => 'rongai town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'ngong hyper',
                'description' => 'ngong hyper market',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'ronald ngala',
                'description' => 'ronald ngala str',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tuskys otc',
                'description' => 'otc nairobi',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivas kawangware',
                'description' => 'kawangware',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'trm',
                'description' => 'thika road mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'garden city',
                'description' => 'garden city mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'thika two',
                'description' => 'commercial str. thika',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'thika one',
                'description' => 'uhuru street',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'thika 5',
                'description' => 'workshop rd, thika',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nyeri 3',
                'description' => 'mbaki hse',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'karatina',
                'description' => 'opposite karatina open air market',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'karatina 2',
                'description' => 'karatina',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'thika 3',
                'description' => 'crossroad junc.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'meru 1',
                'description' => 'njuri njeke rd.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'meru 2',
                'description' => 'njuri njeke rd.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'meru 3',
                'description' => 'njuri njeke rd.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'cedar mall',
                'description' => 'cedar mall nanyuki',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'ananas mall - thika',
                'description' => 'ananas mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'maua  bata',
                'description' => 'kenyatta rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nakumatt meru',
                'description' => 'njuri njeke rd.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mwea bata',
                'description' => 'embu-nbi highway',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'chuka 1',
                'description' => 'chuka',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'chuka 2',
                'description' => 'chuka',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kerugoya 1',
                'description' => 'kerugoya',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mugo nanyuki 1',
                'description' => 'nanyuki',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mugo nanyuki 2',
                'description' => 'nanyuki',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'akai mall',
                'description' => 'akai mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'juja mall',
                'description' => 'juja mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mombasa one',
                'description' => 'diamond trust bld',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'msa post office',
                'description' => 'digo rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'msa marikiti',
                'description' => 'digo rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'msa fontanella',
                'description' => 'moi avenue',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mombasa five',
                'description' => 'msanifu kombo str.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mombasa 6',
                'description' => 'mombasa',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'gateway diani ',
                'description' => 'gateway mall diani',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tuskys mtwapa',
                'description' => 'mtwapa',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'bata ukunda',
                'description' => 'ukunda',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'voi one',
                'description' => 'main street',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'msa kinoiyo',
                'description' => 'digo rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'jubilee arcade',
                'description' => 'jubilee arcade',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'city mall nyali',
                'description' => 'nyali city mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivas nyali',
                'description' => 'nyali',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'airport mall',
                'description' => 'mombasa airport',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tuskys kilifi',
                'description' => 'kilifi',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'bamburi',
                'description' => 'likoni',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'malindi 2 (oasis)',
                'description' => 'oasis mall malindi',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kisumu three',
                'description' => 'oginga odinga rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'united mall bata',
                'description' => 'united mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kisumu one',
                'description' => 'oginga odinga rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kisumu two',
                'description' => 'oginga odinga rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tuff foam mall',
                'description' => 'kisumu',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kiango kisii',
                'description' => 'kisii town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kakamega two',
                'description' => 'kakamega town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kakamega 4 ',
                'description' => 'mega plaza',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kakamega one',
                'description' => 'kenyatta ave.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kericho one',
                'description' => 'kericho',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'migori one',
                'description' => 'migori',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'nakumatt city',
                'description' => 'kenyatta rd kisumu',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'busia bata',
                'description' => 'border town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'siaya bata',
                'description' => 'siaya town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tuskys kisii',
                'description' => 'kisii town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'green sq.mall',
                'description' => 'greensquare mall kericho',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kisumu mega plaza',
                'description' => 'mega plaza kisumu',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'naivas kisumu',
                'description' => 'kisumu',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'westend bata',
                'description' => 'westend mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'boma kisii',
                'description' => 'kisii town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'keroka bata',
                'description' => 'keroka',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'awendo',
                'description' => 'awendo',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'ksm milimani',
                'description' => 'milimani mall kisumu',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'eld kinoiyo 1',
                'description' => 'oginga odinga rd eldoret',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'bungoma one',
                'description' => 'moi avenue bungoma',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'obwaa eld',
                'description' => 'nandi road eldoret',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'eld kinoiyo 2',
                'description' => 'oloo aringo rd.',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kitale one',
                'description' => 'oginga odinga rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kitale 2',
                'description' => 'kenyatta street kitale',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'eldoret one',
                'description' => 'uganda road eldoret',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'rupa mall',
                'description' => 'rupa mall eldoret',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'eld kinoiyo 3',
                'description' => 'nrbi - eldoret rd',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kapsabet bata',
                'description' => 'kapsabet',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'tuskys eldoret',
                'description' => 'tuskys supermarket',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'mumias',
                'description' => 'mumias town',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'eld kinoiyo 4',
                'description' => 'eldoret',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'kitale mall',
                'description' => 'kitale mall',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'khetia euro',
                'description' => 'khetia supermarket',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'khetia cross rds.',
                'description' => 'khetia supermarket',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'khetia eldoret',
                'description' => 'eldoret',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ],
            [
                'name' => 'khetia block/checkpoint',
                'description' => 'eldoret',
                'gradient' => 'danger',
                'image' => 'city-1.jpg',
                'link' => 'KR',
            ]
        ];

        foreach ($locations as $location){
            Locations::create($location);
        }
    }
}
